In [ ]:
import os
import mysql.connector
from mysql.connector import errors

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Database credentials
DB_CONNECTION = os.getenv('DB_CONNECTION')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_DATABASE = os.getenv('DB_DATABASE')
DB_USERNAME = os.getenv('DB_USERNAME')
DB_PASSWORD = os.getenv('DB_PASSWORD')

# Connect to the database
try:
    conn = mysql.connector.connect(
        host=DB_HOST,
        port=DB_PORT,
        database=DB_DATABASE,
        user=DB_USERNAME,
        password=DB_PASSWORD
    )
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM your_table;")
    rows = cursor.fetchall()
    cursor.close()
    print(rows)
except errors.ProgrammingError as err:
    print(f"Error connecting to MySQL: {err}")
finally:
    conn.close()


In [5]:
import torch
import cv2
from utils import (
    collate_fn,
    get_transform,
    myOwnDataset,
)
import config
from eval import evaluate_model
import model

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

# Load the PyTorch model
model =  model.get_model(device=device, model_name='v2')
model.load_state_dict(torch.load('models/bigData.pth', map_location=torch.device('cpu')))

# Create test Dataset
testing_dataset = myOwnDataset(
    root=config.data_dir, annotation=config.test_coco, transforms=get_transform()
)

# Testing DataLoader
testing_loader = torch.utils.data.DataLoader(
    testing_dataset,
    batch_size=config.test_batch_size,
    shuffle=config.train_shuffle_dl,
    num_workers=config.num_workers_dl,
    collate_fn=collate_fn,
)


# Evaluate the model
output = evaluate_model(model.to(device), device, testing_loader, "notrans")

# Print the output
print(output)


loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[18]
labels: 
['Santander']
[]
[20 27 20 20 27 20 22 20 20]
labels: 
['Scandic', 'Telenor', 'Scandic', 'Scandic', 'Telenor', 'Scandic', 'SpareBank1SMN', 'Scandic', 'Scandic']
['SpareBankSR', 'SpareBankSR']
[15 15 18 18 15 18 18 18 15 15 18 18 20 21 15 18 18]
labels: 
['Lyse', 'Lyse', 'Santander', 'Santander', 'Lyse', 'Santander', 'Santander', 'Santander', 'Lyse', 'Lyse', 'Santander', 'Santander', 'Scandic', 'Sparebank1NordNorge', 'Lyse', 'Santander', 'Santander']
['Lyse', 'Altibox', 'Lyse', 'Lyse', 'Lyse', 'Lyse', 'Santander', 'Santander', 'Santander', 'Lyse', 'Lyse', 'Santander', 'Santander']
[ 9 17 18 22  9  3  9]
labels: 
['DNB', 'OBOS', 'Santander', 'SpareBank1SMN', 'DNB', 'bama', 'DNB']
['Sparebanken M¢re', 'OBOS', 'bama', 'DNB']
[]
labels: 
[]
[]
[ 9 18 20 20 20]
labels: 
['DNB', 'Santander', 'Scandic', 'Scandic', 'Scandic']
[]
[18  2  2 18  9]
labels: 
['Santander', 'Altibox', 'Altibox', 'Santande

KeyboardInterrupt: 

: 